//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.App_core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Nhanvien()
        {
            this.tbl_Bienban = new HashSet<tbl_Bienban>();
        }
    
        public string PK_sMaNV { get; set; }
        public string sTenNV { get; set; }
        public Nullable<System.DateTime> dNgaysinh { get; set; }
        public string sGioitinh { get; set; }
        public string sCCCD { get; set; }
        public string sDiachi { get; set; }
        public string sSDT { get; set; }
        public string sEmail { get; set; }
        public Nullable<System.DateTime> dNgayvaolam { get; set; }
        public Nullable<double> fLuongcb { get; set; }
        public string sTinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bienban> tbl_Bienban { get; set; }
    }
}
